---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-org2
  labels:
    app: chaincode-basic-org2
spec:
  selector:
    matchLabels:
      app: chaincode-basic-org2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-org2
    spec:
      containers:
        - image: majedur708/hlf-api:12.6
          name: chaincode-basic-org2
          imagePullPolicy: Always
          env:
            - name: CHAINCODE_ID
              value: "basic:107a30bb85ddbc5167e2347acb3485de1f2a6f12f9ad0359ce9d25d44d3f68d7"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
